config/routes.rb
Rails.application.routes.draw do
  root 'tickets#index'

  resources :tickets
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  validates :uw_name, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  def index
    @incomplete_tickets = Ticket.where(complete: false).order('tickets.second_signature DESC', 'tickets.created_at ASC')
    @complete_tickets = Ticket.where(complete: true).order('tickets.created_at ASC')
  end

  def show
    @ticket = Ticket.find(params[:id])
  end

  def new
    @ticket = Ticket.new
    respond_to do |format|
      format.html { redirect_to tickets_path }
      format.js
    end
  end

  def create
    @ticket = Ticket.new(ticket_params)
    @ticket.save
    respond_to do |format|
      format.html { redirect_to tickets_path }
      format.js
    end
  end

  def edit
    @ticket = Ticket.find(params[:id])
  end

  def update
    @ticket = Ticket.find(params[:id])
    @ticket.update(ticket_params)
    respond_to do |format|
      format.html { redirect_to tickets_path }
      format.json { head :ok }
      format.js
    end
  end

  def destroy
    @ticket = Ticket.find(params[:id])
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to tickets_path }
      format.js
    end
  end

private
  def ticket_params
    params.require(:ticket).permit(:uw_name, :complete,
                                    :loan_number, :notes,
                                    :second_signature)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link href='//fonts.googleapis.com/css?family=Droid+Sans:400,700|Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <title><%= yield(:title) %></title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= image_tag("logo.png", id: "logo") %>
      <h1>Test Queue</h1>
    </header>

    <main>

      <%= flash[:alert] %>
      <%= flash[:notice] %>

      <%= yield %>

    </main>
  </body>
</html>

app/views/tickets/_form.html.erb
<%= render 'layouts/errors', object: @ticket %>

<%= form_for @ticket, remote: true do |f| %>
  <section>
    <h3>Create Ticket</h3>
    <%= f.label :uw_name do %>
      <%= content_tag(:span, "UW Name:") %>
      <%= f.text_field :uw_name %>
    <% end %>
    <%= f.label :loan_number do %>
      <%= content_tag(:span, "Loan Number:") %>
      <%= f.text_field :loan_number %>
    <% end %>
    <%= f.label :notes do %>
      <%= content_tag(:span, "2nd Signature:") %>
      <%= f.check_box :second_signature %>
    <% end %>
    <%= f.submit %>
  </section>
<% end %>

app/views/tickets/_ticket.html.erb
<%= form_for ticket, remote: true do |f| %>
  <%= f.check_box :complete %>
  <%= f.submit "Update" %>
  <%= best_in_place ticket, :uw_name %> |
  <%= best_in_place ticket, :loan_number %> |
  <%= best_in_place ticket, :second_signature, as: :checkbox, collection: {false: "2nd Signature: NO", true: "2nd Signature: YES"} %>
  <%= link_to "Delete", ticket,
                        data: {confirm: "Are you sure?", method: :delete},
                        remote: true %>
<% end %>

app/views/tickets/create.js.erb
$('#new_ticket').remove();
$('#new_link').show();
$('#incomplete_tickets').append('<%= j render(@ticket) %>');
$('#edit_ticket_<%= @ticket.id %>').submitOnCheck();

app/views/tickets/destroy.js.erb
$('#edit_ticket_<%= @ticket.id %>').remove();

app/views/tickets/edit.html.erb
<% content_for(:title, "Edit ticket") %>

<h1>Edit ticket</h1>

<%= render 'form' %>

app/views/tickets/index.html.erb
<% content_for(:title, "Test Queue") %>

<p>
  <%= link_to "New Ticket", new_ticket_path, class: "ghost-button", id: "new_link", remote: true %>
</p>

<section>
    <h3>Active Tickets</h3>
    <div class="row" id="incomplete_tickets">
      <%= render @incomplete_tickets %>
    </div>
</section>

<section>
    <h3>Completed Tickets</h3>
    <div class="row" id="complete_tickets">
      <%= render @complete_tickets %>
    </div>
</section>

app/views/tickets/new.html.erb
<% content_for(:title, "New ticket") %>

<h1>New ticket</h1>

<%= render 'form' %>

app/views/tickets/new.js.erb
$('#new_link').hide().after('<%= j render("form") %>');

app/views/tickets/show.html.erb
<% content_for(:title, "Ticket #{@ticket.id}") %>

<h1>Ticket <%= @ticket.id %></h1>

<h3><%= @ticket.description %></h3>

<p>
  <%= link_to "Edit", edit_ticket_path(@ticket) %> |
  <%= link_to "Delete", ticket_path(@ticket),
                        data: {confirm: "Are you sure?",
                                method: "delete"} %> |
  <%= link_to "Mark as complete", ticket_path(ticket: {complete: true}),
                                method: :put %>
</p>

<p>
  <%= link_to "Return to queue", tickets_path %>
</p>

app/views/tickets/update.js.erb
<% if @ticket.complete? %>
  $('#edit_ticket_<%= @ticket.id %>').appendTo('#complete_tickets');
<% else %>
  $('#edit_ticket_<%= @ticket.id %>').appendTo('#incomplete_tickets');
<% end %>